### PR TITLE
Compatibilty with v0.8 context plus specs

### PR DESCRIPTION
**Pull request by sjones6**
Fixes issue #38 .

FYI @kavaro.

### CODE REVIEW

**Comment by sjones6** [comment]
@PsychoLlama : let me know when you can check this out so we can keep up compatibility with v0.8. :)

**Comment by amark** [comment]
The only reason these tests are failing is because of some JSDoc / ESLint stuff (it doesn't show any of the actual tests failing). I don't know how to fix those things though :/.

@sjones6 how are you doing! Congrats BTW, I hope you and your family are doing well!

**Comment by PsychoLlama** [comment]
@sjones6 looks good to me 👍
Thanks for tackling this!

For the `.spec` files, I'll usually toss in an `/* eslint-disable require-jsdoc */` at the top. That should fix some of the lint errors.

**Comment by sjones6** [comment]
Thanks @amark and @PsychoLlama . Just fixed those linting errors and we're good to go. :)

**Comment by amark** [comment]
w00h00!

**Comment by PsychoLlama** [comment]
@sjones6 should I draft a new major version release for npm?

**Comment by sjones6** [comment]
@PsychoLlama : I just did a `npm version patch && git push --tags` (which I think should rollout a patch version deploy?). 

Seems like a patch version was sufficient, but apologies if that was a misstep.

**Comment by PsychoLlama** [comment]
@sjones6 yep, that'll publish it! 👌 

I took a look at the build logs though and it seems I haven't updated this repo recently. Travis CI made a subtle breaking change where they stash everything (including untracked files) after the scripts run... including node_modules :worried:

So the publish will fail until the `skip_cleanup` option is added to the `.travis.yml` file. It's weird. ([source](https://docs.travis-ci.com/user/deployment#Uploading-Files))

**Comment by sjones6** [comment]
Oh, yeah. Good catch.

Can you tackle that trouble tonight? I won't be able to until tomorrow.

**Comment by PsychoLlama** [comment]
Sure thing! It's broken a few of my deploys in other projects, so I've got some practice :wink:

**Comment by PsychoLlama** [comment]
Surgery complete. v6.0.2 is live :tada:

**Comment by kavaro** [comment]
Thanks for this, works perfectly …

El 29 oct 2017, a las 1:47, Jesse Gibson <notifications@github.com<mailto:notifications@github.com>> escribió:


Surgery complete. v6.0.2 is live 🎉

**Pull request merged**
